### ISSUE TITLE
Virus warning

### ISSUE THREAD

**Issue by Forecaster** [Koken-Community-Support/Social-Share-Kit-for-Koken#3]
When trying to download the source in chrome it refused saying there was a virus detected in the archive.

Bypassing that by downloading it with firefox instead, but trying to upload the files to my server my sftp client refused to upload the file "social-share-kit.js" saying it contains a virus.

**Comment by BlackSkorpio** [comment]
Can you be more specific?
`social-share-kit.js` does not contain any code that could damage your, or anyone else, computer...

**Comment by Forecaster** [comment]
Hm, at work right now, re-downloaded the source and it worked, also uploaded correctly. Going to have to re-try at home and see if I can get more details from it.

**Comment by BlackSkorpio** [comment]
Sounds very much as a false positive from your soft at home

**Comment by Forecaster** [comment]
It seems to be the Windows 10 Attachment Manager that is doing it. I have no anti-virus software other than windows built-in system. Both Chrome and WinSCP might allow that to prevent handling untrusted files. Though Firefox ignored it.
